
server:
  port: 8085
spring:
  application:
    name: SupplierNPH
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
          jwk-set-uri: ${JWT_JWK_SET_URI}