server:
  port: 8085

spring:
  application:
    name: product

  r2dbc:
    url: ${DATABASE_URL}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
          jwk-set-uri: ${JWT_JWK_SET_URI}
